### ISSUE TITLE
8M 3D points cause out of memory?

### ISSUE THREAD

**Issue by willdzeng** [aaalgo/kgraph#14]
I am trying to use kgraph to search nearest neighbors in large numbers of 3d points (around 8M, float).
But the memory consumption went to 12G when I build them, and killed itself for some reason.
In general, does kgraph good at low dimensional data?

Thank you.

> Generating control...
> Initializing...
> iteration: 1 recall: 0 accuracy: 5598.69 cost: 4.60438e-05 M: 8.81314 delta: 1 time: 56.845 one-recall: 0 one-ratio: 1681.14
> iteration: 2 recall: 0.0004 accuracy: 653.841 cost: 6.64835e-05 M: 8.81314 delta: 0.958052 time: 97.4261 one-recall: 0 one-ratio: 239.893
> iteration: 3 recall: 0.0056 accuracy: 78.795 cost: 9.06406e-05 M: 10.6469 delta: 0.957443 time: 141.039 one-recall: 0.04 one-ratio: 37.5534
> iteration: 4 recall: 0.0696 accuracy: 8.98511 cost: 0.000114621 M: 10.6864 delta: 0.951843 time: 184.422 one-recall: 0.26 one-ratio: 5.3301
> iteration: 5 recall: 0.48 accuracy: 0.913621 cost: 0.00013838 M: 10.82 delta: 0.897214 time: 226.866 one-recall: 0.85 one-ratio: 1.21359
> iteration: 6 recall: 0.9696 accuracy: 0.0216504 cost: 0.000161372 M: 11.7296 delta: 0.556845 time: 264.739 one-recall: 1 one-ratio: 1
> iteration: 7 recall: 1 accuracy: 0 cost: 0.000199729 M: 18.025 delta: 0.205682 time: 316.05 one-recall: 1 one-ratio: 1
> Killed
> 

I am wondering is this normal, maybe the way I am using is wrong?
```c++
typedef kgraph::MatrixOracle<float, kgraph::metric::l2sqr> Oracle;
typedef kgraph::Matrix<float> Matrixf;
void InitCopyData(const std::vector<Eigen::Vector3f>& points,
    const std::vector<Eigen::Vector3f>* normals) {
  Matrixf data(points.size(), 3);
  for (uint32_t i = 0; i < points.size(); i++) {
    float* row = data[i];
    for (int j = 0; j < 3; j++, row++) {
      *row = points[i](j);
    }
  }
  oracle_.reset(new Oracle(data));
  LOG(INFO) << "Finished Copying";
  kgraph::KGraph::IndexParams params;
  params.K = 25;
  params.L = 100;
  params.S = 10;
  params.R = 100;
  params.controls = 100;
  params.recall = 0.99;
  params.delta = 0.002;
  params.reverse = 0;

  LOG(INFO) << "Building kgraph";
  index_->build(*oracle_.get(), params);
  LOG(INFO) << "Finished building kgraph";
}
```

**Comment by aaalgo** [comment]
Unfortunately 8M points does cost that much memory.  Try set params.L = 
50; which will reduce memory consumption.  If that works for you, I 
would go ahead and make the following adjustments:

params.K = 15;
params.L = 50;        // if you still get OOM, further reduce that to 30.
params.S = 10;
params.R = 50;

That will make the program run much faster.  3D is easy case anyway.

- Wei

**Comment by willdzeng** [comment]
Thanks for the parameters, it works now!
