### ISSUE TITLE
Finding out number of distances computed when `reverse=-1`

### ISSUE THREAD

**Issue by govinda-kamath** [aaalgo/kgraph#22]
We were trying estimate the scan rate (as defined in [your paper](http://www.cs.princeton.edu/cass/papers/www11.pdf)) of your algorithm on tiny-imagenet. 

On setting `reverse=0` , this is the number of total distance evaluations iterations*K^2 if I understand correctly. However, I was wondering how one could obtain the total number of distance evaluations when `reverse=-1` from the code.

Also what do the parameters `L`, `M`, `P`, `S`, `T` mean?

**Comment by aaalgo** [comment]
I checked the code.  The API was designed such that if `SearchInfo *` is passed in, the `cost` fields should be set to the number of comparison divided by number of points.  I checked the code, the number is not calculated correctly.

The way that's guaranteed to work is to implement your own SearchOracle with a `std::atomic<size_t>` to count the number, and add to it in `operator ()`.

I have some old documentation in the format of pmwiki.  I think what you want is in http://www.kgraph.org/wiki.d/Main.Tutorial .  You can open it and search for "Now you can tweak searching by specifying a "K" parameter..." and start reading. 

T is newer than the wiki page.  It means to do the query process T times and combine the results for better accuracy.

**Comment by govinda-kamath** [comment]
Thanks a ton.
