### ISSUE TITLE
Example for CPP

### ISSUE THREAD

**Issue by richarmony** [aaalgo/kgraph#24]
Hello aaalgo,

I'm a CPP noob and I'm wondering how to use your code in CPP. (I have no doubt for python's API)

Could you provide an example of how to extend class IndexOracle and SearchOracle in CPP (maybe with Euclidean distance)? Do I have to save such class in additional .h .cpp?

**Comment by aaalgo** [comment]
https://github.com/aaalgo/kgraph/blob/master/kgraph-data.h  -- Definition of oracles for L2.
https://github.com/aaalgo/kgraph/blob/master/index.cpp
https://github.com/aaalgo/kgraph/blob/master/search.cpp

**Comment by richarmony** [comment]
Ok, So I should do the same as "class MatrixOracle" implementation... thank you, I'll give it a try :)

**Comment by aaalgo** [comment]
If you only need L2, use the pre-defined oracle which is optimized with SSE.  You can modify index.cpp and search.cpp to meet your needs.

**Comment by richarmony** [comment]
Actually, I'm working with Mahalanobis Distances, but I think L2 is close enough, especially if it is optimized with SSE and AVX. Thank you :D
