### ISSUE TITLE
kgraph.cpp has a minor bug or not a bug

### ISSUE THREAD

**Issue by gchen2101** [aaalgo/kgraph#26]
line 822 and 823 of kgraph.cpp:
nhoods[j].parallel_try_insert(i, dist);
if (r < params.K) ++uu;
should be 
r = nhoods[j].parallel_try_insert(i, dist);
if (r < params.K) ++uu;
<img width="519" alt="kgraph" src="https://user-images.githubusercontent.com/21057235/45674838-7e003f00-bb60-11e8-9016-71011b995ddc.png">

**Comment by justdoit1990** [comment]
Something may be changed in you code. My code is right.

for (unsigned n = 0; n < oracle.size(); ++n) {
                size_t uu = 0;
                nhoods[n].found = false;
                nhoods[n].join([&](unsigned i, unsigned j) {
                        float dist = oracle(i, j);
                        ++cc;
                        unsigned r;
                        r = nhoods[i].parallel_try_insert(j, dist); 
                        if (r < params.K) ++uu;   
                        r = nhoods[j].parallel_try_insert(i, dist);
                        if (r < params.K) ++uu;
                });

**Comment by gchen2101** [comment]
Thank you for your quick response.
Would you update github with the right code?
