### ISSUE TITLE
question about rnn

### ISSUE THREAD

**Issue by gchen2101** [aaalgo/kgraph#29]
Hi, my question is why put a condition 
`if (nn.dist > nhood_o.radiusM) `
when form reverse nodes.
Thanks!

![image](https://user-images.githubusercontent.com/21057235/46243096-b1658800-c402-11e8-981d-e3157c48af31.png)

**Comment by aaalgo** [comment]
Adding reverse K-NN to the graph is to bring in the long-range connections that are useful to keep the points connected and hence the ">" test.  But you can try remove that and see how speed & accuracy change.

**Comment by gchen2101** [comment]
Thank you very much for your quick answer!
">" test is good to avoid rnn_new duplicates nodes existing in nn_new.
In another word, if we remove ">" test, rnn_new may have duplicated nodes. Moreover the subset of rnn_new that is added in when ">" test is removed may have duplicated nodes as well as new nodes. These new nodes may be a lose if we have ">" test.
