### ISSUE TITLE
kgraph-data.h error

### ISSUE THREAD

**Issue by daekp** [aaalgo/kgraph#31]
I'm trying building and installation.

but I have an error and can not build it. The file is kgraph-data.h.

The error is as follows.

In file included from /root/Regard3D/src/thirdparty/kgraph/metric.cpp:2:0:
/root/Regard3D/src/thirdparty/kgraph/kgraph-data.h: In member function ‘void kgraph::Matrix<T, A>::reset(unsigned int, unsigned int)’:
/root/Regard3D/src/thirdparty/kgraph/kgraph-data.h:109:28: error: there are no arguments to ‘memalign’ that depend on a template parameter, so a declaration of ‘memalign’ must be available [-fpermissive]
             data = (char *)memalign(A, row * stride); // SSE instruction needs data to be aligned
                            ^~~~~~~~
/root/Regard3D/src/thirdparty/kgraph/kgraph-data.h:109:28: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
thirdparty/kgraph/CMakeFiles/kgraph.dir/build.make:86: recipe for target 'thirdparty/kgraph/CMakeFiles/kgraph.dir/metric.cpp.o' failed
make[2]: *** [thirdparty/kgraph/CMakeFiles/kgraph.dir/metric.cpp.o] Error 1
CMakeFiles/Makefile2:403: recipe for target 'thirdparty/kgraph/CMakeFiles/kgraph.dir/all' failed
make[1]: *** [thirdparty/kgraph/CMakeFiles/kgraph.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by aaalgo** [comment]
I think the problem is that "memalign" is not declared.  Try "#include <malloc.h>" and let me know.

**Comment by amkatrutsa** [comment]
Hello! 
I use MacOS and want to compile your library. But firstly Clang told me that it can not find malloc.h. I follow recommendations to replace malloc.h with stdlib.h, and it finds this file. But secondly, Clang raised the error that @daekp reported. Is your library portable to MacOS? And how I can solve this issue with allocating aligned memory? Thanks in advance!

**Comment by aaalgo** [comment]
It's this problem: https://stackoverflow.com/questions/196329/osx-lacks-memalign
According to the page, malloc returns are aligned to 16 bytes which I think is sufficient, you can simply replace memalign(A, row * stride) by malloc(row * stride).
I don't have MacOS environment so I cannot test it for you.

**Comment by amkatrutsa** [comment]
Thanks! Does the library become slower without aligned memory?

**Comment by aaalgo** [comment]
No.  The memory from malloc IS aligned, so memalign is not needed on Mac.

**Comment by amkatrutsa** [comment]
Ok, thanks a lot!
