### ISSUE TITLE
Python API: directly loading saved index without dataset

### ISSUE THREAD

**Issue by jiaxinwoo** [aaalgo/kgraph#36]
Thank you for sharing this project. It is very fast and powerful. 

I wonder if there is a way to use the saved index without loading the raw features in python API.
I mean in the current python version, we need to doing the following steps to save the index.
--------------- first time ----------------------
index = pykgraph.KGraph(dataset, 'euclidean')  # another option is 'angular'
index.build(reverse=-1)                       
index.save("index_file");
---------------------------------------------
and when we use it next time, we need to
--------------next time--------------------
index = pykgraph.KGraph(dataset, 'euclidean')  
index.load("index_file")
-------------------------------------------
I wonder if we can do something like this to create the index and load the saved index without loading the raw feature again? Because in my program, raw feature is really big and it takes a lot memory.... 
--------------something like this--------------------
index = pykgraph.KGraph()  
index.load("index_file")
----------------------------------------------------
P.S. http://www.kgraph.org/ seems not working. Is there any document available online about the usages of kgraph?
Thank you so much.

**Comment by aaalgo** [comment]
The index cannot work without feature data.  You might want to try 
dimension reduction techniques to reduce feature size.

**Comment by jiaxinwoo** [comment]
OK. Thank you for the reply
