### ISSUE TITLE
Returning both IDs and distances in python api

### ISSUE THREAD

**Issue by jonbakerfish** [aaalgo/kgraph#4]
Is it possible to return both ids and distances in python api? Can I follow [this line of code](https://github.com/aaalgo/kgraph/blob/master/python/pykgraph.cpp#L64) but replace the `NULL` to something like`const_cast<float *>(distmatrix[i])` where:

```
PyObject *distance =  PyArray_SimpleNew(2, dims, NPY_FLOAT);
kgraph::MatrixProxy<float, 1> distmatrix(reinterpret_cast<PyArrayObject *>(distance));
```

What else should I change?

**Comment by aaalgo** [comment]
Change the following two lines to get the distance values.

 61         if (hasIndex) {
 62 #pragma omp parallel for reduction(+:cost)
 63             for (unsigned i = 0; i < qmatrix.size(); ++i) {
 64                 index->search(oracle.query(qmatrix[i]), params, const_cast<unsigned *>(rmatrix[i]), NULL);

 index->search(oracle.query(qmatrix[i]), params, const_cast<unsigned *>(rmatrix[i]), const_cast<float *>(distmatrix[i]));

 65             }
 66         }
 67         else {
 68 #pragma omp parallel for reduction(+:cost)
 69             for (unsigned i = 0; i < qmatrix.size(); ++i) {
 70                 oracle.query(qmatrix[i]).search(params.K, params.epsilon, const_cast<unsigned *>(rmatrix[i]),  const_cast<float *>(distmatrix[i]) );
 71             }
 72         }

I'm not sure what's the python common practice to return multiple values.

**Comment by jonbakerfish** [comment]
@aaalgo I modify these two line in [this commit](https://github.com/jonbakerfish/kgraph/commit/0c9ee8e765d1e4561787ef2432a1f551e2e99bb0), however the result is not correct when returning with distance by:
`result,distance = index.search(dataset, query, K=100, threads=30,withDistance=True)` compared with the
`result = index.search(dataset, query, K=100, threads=30,withDistance=False)`.

Can you help figuring it out?

**Comment by aaalgo** [comment]
You already figured it out and fixed my bug.
