### ISSUE TITLE
Sample command lines

### ISSUE THREAD

**Issue by dumbogeorge** [aaalgo/kgraph#41]
I would like to request sample command lines for running ./search and ./index. In what format do I need to provide data set for both executables and in what format do I need to give query inputs?

How should we feed a dataset as input to the search and index excutables. What should format of dataset ?

**Comment by aaalgo** [comment]
Thanks for your interest.  But this piece of software was developed a decade ago, and the command line no longer make much sense today.   If you need the algo, the best way is to integrate it as a C++ library.
