### ISSUE TITLE
[Improvement] batch methods for oracle interfaces

### ISSUE THREAD

**Issue by CharlesJQuarra** [aaalgo/kgraph#42]
I see that both `IndexOracle` and `SearchOracle` compare one entity pair at a time, this leaves on the table room for these backends amortize access overheads over a batch of entities to retrieve, specially if the entities have to be retrieved from an key-value object store

**Comment by aaalgo** [comment]
This library, and most similar algorithms as I'm aware of, are not designed to support running against a vector store.  Kgraph assumes direct memory access, and target data sets which takes minutes to index.
