### ISSUE TITLE
Header conflict when building with new versions of Boost

### ISSUE THREAD

**Issue by sageshoyu** [aaalgo/kgraph#43]
When building with Boost 1.74, I ran into an issue where there is a conflicting header file with the `version` file found in the top level of this repository.

I resolved the issue by renaming the `version` file [(linked here)] (https://github.com/aaalgo/kgraph/blob/master/version) to a different name  (e.g. `_version`). 

Turns out that `version` is now a standard Cpp header, re: this discussion here: https://github.com/boostorg/config/issues/345

Changing the `version` filename permanently would resolve this issue for any users compiling with newer versions of Boost.

Thank you!

**Comment by aaalgo** [comment]
Removed.

**Comment by sageshoyu** [comment]
Thank you!
