### ISSUE TITLE
`Floating point exception (core dumped)` during  searching

### ISSUE THREAD

**Issue by jonbakerfish** [aaalgo/kgraph#6]
I got an error when using the python search api, run `index.search(dataset, query, K=100, P=1000, threads=0)` and the program crashed down and got `Floating point exception (core dumped)`. However, when `P` equals to other values, say 1001, 2000, 10000 etc, there's no such an error. Here's the code:

```
from numpy import random
import pykgraph
dataset = random.rand(1000, 4096)
index = pykgraph.KGraph()
index.build(dataset)
query = random.rand(1, 4096)
r1      = index.search(dataset, query, K=100, P=1000, threads=0, withDistance=False)
r2,dist = index.search(dataset, query, K=100, P=1000, threads=0, withDistance=True)
```

**Comment by jonbakerfish** [comment]
It seems that the error comes from `kgraph.cpp` in function: `static void GenRandom (RNG &rng, unsigned *addr, unsigned size, unsigned N)` in line 37:

```
Program received signal SIGFPE, Arithmetic exception.
(rng=..., addr=addr@entry=0x2eb5b50, size=1000, N=1000) at kgraph.cpp:37
37                  addr[i] = rng() % (N - size);
```

**Comment by aaalgo** [comment]
I think the problem here is obvious: number of points in the dataset must be larger than P for KGraph to work.  It is a bug.  I'll fix it today.

**Comment by aaalgo** [comment]
I've commited a fix.  It's not by fixing GenRandom.  Rather, if the dataset is too small, brutal force search is used instead of index.  Please test if that fixes your problem.

**Comment by jonbakerfish** [comment]
Work like a charm. Thanks.
