### ISSUE TITLE
python search wrapper error

### ISSUE THREAD

**Issue by jonbakerfish** [aaalgo/kgraph#8]
Hi, I'm using the python wrapper `index.search` to retrieve nearest neighbor, but got this error:

```
python: ../kgraph-data.h:191: kgraph::MatrixProxy<DATA_TYPE, A>::MatrixProxy(PyArrayObject*) [with DATA_TYPE = float; unsigned int A = 16u; PyArrayObject = tagPyArrayObject_fields]: Assertion`stride % A == 0' failed.
```

Any idea?

**Comment by aaalgo** [comment]
Input dimension has to be multiple of 4.  You have to pad it with 0 if not.  I'm sorry it's not well documented.

**Comment by jonbakerfish** [comment]
Do I need to padding the query only, or both query and the indexed matrix?

**Comment by aaalgo** [comment]
You need to pad both.  An alternative is to replace kgraph::metric::l2sqr::{norm2, dot} with your own code.  My version uses some hand-coded SSE2 instruction in hope of speedup and assumes a stride of multiple of 16 bytes (4xfloats).
